apiVersion: v1
name: helm-otrs
version: 0.1
description: helm chart for mariadb-otrs
sources:
    - juanluisbaptiste/otrs-mariadb
maintainers:
  - name: rkeri
  - url: rkeri/helm-mariadb-otrs
appVersion: 1.0
